"""Prepare the data for the interactive dashboard (docs/index.html).

Uses the same cleaning rules as food_waste_analysis.ipynb and writes docs/data.js.
Run from the project folder:  .venv\\Scripts\\python scripts\\build_dashboard_data.py
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

ROOT = Path(__file__).resolve().parent.parent
SECTORS = ["Household", "Out-of-home consumption", "Retail"]

# --- Food waste, 2022, real countries only (same rules as the notebook) ---
waste = pd.read_csv(ROOT / "data" / "food-waste-per-capita.csv")
w22 = waste[waste["Year"] == 2022].copy()
w22["Total"] = w22[SECTORS].sum(axis=1)
world = w22[w22["Entity"] == "World"].iloc[0]

countries = w22[w22["Code"].fillna("").str.fullmatch("[A-Z]{3}")].dropna(subset=SECTORS)
countries = countries[countries["Total"] > 0].copy()
# A household value shared with another country is likely estimated, not measured
countries["estimated"] = countries["Household"].duplicated(keep=False)

# --- GDP per person and continent, 2022 ---
gdp = pd.read_csv(ROOT / "data" / "gdp-per-capita-worldbank.csv")
gdp22 = gdp.loc[gdp["Year"] == 2022, ["Code", "GDP per capita", "World region according to OWID"]]
countries = countries.merge(gdp22, on="Code", how="left")

# --- Headline statistics shown on the dashboard ---
m = countries.dropna(subset=["GDP per capita"]).rename(columns={"World region according to OWID": "region"})
m["log10_gdp"] = np.log10(m["GDP per capita"])
rank_corr = m["Household"].rank().corr(m["GDP per capita"].rank())
r2_gdp_only = smf.ols("Household ~ log10_gdp", data=m).fit().rsquared
with_region = smf.ols("Household ~ log10_gdp + C(region)", data=m).fit(cov_type="HC3")

india_rank = int(countries["Household"].rank(ascending=False)[countries["Entity"] == "India"].iloc[0])


def r1(x):
    return None if pd.isna(x) else round(float(x), 1)


data = {
    "world": {"household": r1(world["Household"]), "outOfHome": r1(world["Out-of-home consumption"]),
              "retail": r1(world["Retail"]), "total": r1(world["Total"])},
    "stats": {
        "countries": len(countries),
        "withGdp": len(m),
        "rankCorr": round(float(rank_corr), 2),
        "r2GdpOnly": round(float(r2_gdp_only), 3),
        "regionPValue": round(float(with_region.pvalues["log10_gdp"]), 2),
        "indiaHouseholdRank": india_rank,
    },
    "countries": [
        {
            "name": r["Entity"], "code": r["Code"],
            "region": None if pd.isna(r["World region according to OWID"]) else r["World region according to OWID"],
            "household": r1(r["Household"]), "outOfHome": r1(r["Out-of-home consumption"]),
            "retail": r1(r["Retail"]), "total": r1(r["Total"]),
            "gdp": None if pd.isna(r["GDP per capita"]) else round(float(r["GDP per capita"])),
            "estimated": bool(r["estimated"]),
        }
        for _, r in countries.sort_values("Entity").iterrows()
    ],
}

out = ROOT / "docs" / "data.js"
out.parent.mkdir(exist_ok=True)
out.write_text("// Generated by scripts/build_dashboard_data.py - do not edit by hand\n"
               "window.FOOD_WASTE = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n",
               encoding="utf-8")
print(f"Wrote {out.relative_to(ROOT)}: {len(data['countries'])} countries, stats {data['stats']}")
